Add a JIRA Issue ChangeSource
fluendo/buildbot pull request #9
Opened 2019-02-19 14:37 UTC by turran

The idea is generate a change for every changed issue returned
by a JQL. With this patch, buildbot can trigger actions based
on a modification of an issue.

2019-02-27 15:48 UTC, marecki315 requested changes

2019-02-27 15:48 UTC, marecki315 commented on master/buildbot/changes/jirapoller.py
> +from buildbot.util import httpclientservice
httpclientservice imported but not used

2019-02-27 15:48 UTC, marecki315 commented on master/buildbot/changes/jirapoller.py
> +            config.error("The python module 'jira' is needed to use a JIRA "
looks like _config_ is not imported (missing _from buildbot import config_)

2019-02-27 15:48 UTC, marecki315 commented on master/buildbot/changes/jirapoller.py
> +    if t[17]=='+':
Code formatting in this file is inconsistent. Sometimes there are spaces before and after "=", sometimes there are not etc.

2019-02-27 16:11 UTC, marecki315 commented on master/buildbot/changes/jirapoller.py
> +    def checkConfig(self,
user, token, domain, jql parameters are not used in this method

2019-02-27 16:24 UTC, marecki315 commented on master/buildbot/changes/jirapoller.py
> +       ret-=timedelta(hours=int(t[18:20]),minutes=int(t[20:]))
wrong indent (3 spaces, not 4)

2019-03-13 10:52 UTC, turran commented
I've addressed the comments on the fluendo-buildbot PR itself instead of having it here.

2019-03-13 10:52 UTC, closed without merging